c Copyright (C) 2000 

c Questo programma è software libero; è lecito ridistribuirlo e/o
c modificarlo secondo i termini della Licenza Pubblica Generica SMR come
c pubblicata da ARPA SMR ; o la versione 1 della licenza o (a scelta)
c una versione successiva.

c Questo programma è distribuito nella speranza che sia utile, ma SENZA
c ALCUNA GARANZIA; senza neppure la garanzia implicita di
c COMMERCIABILITÀ o di APPLICABILITÀ PER UN PARTICOLARE SCOPO. Si veda
c la Licenza Pubblica Generica SMR per avere maggiori dettagli.

c Ognuno dovrebbe avere ricevuto una copia della Licenza Pubblica
c Generica SMR insieme a questo programma; in caso contrario, la si può
c ottenere da Agenzia Regionale Prevenzione e Ambiente (ARPA) Servizio
c Meteorologico Regionale (SMR), Viale Silvani 6, 40122 Bologna, Italia






	SUBROUTINE RIBALTA(which,MAT,IMAX,JMAX,MATNEW,INEW,JNEW)

CONSTART RIBALTA
c			da verificare !!!!!!!!!!!!!!!
c
C	SUBROUTINE RIBALTA(which,MAT,IMAX,JMAX,MATNEW,INEW,JNEW)
C
C	IN:
C	WHICH		CHARACTER*(*)	OPERAZIONE DA ESEGUIRE:
C		SE WHICH='II'	SCAMBIO ORDINE INDICE I
C		SE WHICH='JJ'	SCAMBIO ORDINE INDICE J
C		SE WHICH='IIJJ'	SCAMBIO ORDINE INDICI I E J
C		SE WHICH='JI'	SCAMBIO LE RIGHE CON LECOLONNE
C		SE WHICH='JII'	SCAMBIO ORDINE INDICE I E RIGHE CON COLONNE
C		SE WHICH='JJI'	SCAMBIO ORDINE INDICE J E RIGHE CON COLONNE
C		SE WHICH='JJII'	SCAMBIO ORDINE INDICE I E J E RIGHE CON COLONNE
C		SE WHICH<> DAI VALORI PRECEDENTI VIENE SCRITTA MATNEW NELLO
C			         STESSO ORDINE DEI DATI FORNITI
C
C	MAT(IMAX,JMAX)		4BYTE	MATRICE IN INPUT
C	IMAX			I*4	PRIMA   DIMENSIONE MATRICE INPUT
C	JMAX			I*4	SECONDA DIMENSIONE MATRICE INPUT
C	INEW			I*4	PRIMA   DIMENSIONE MATRICE OUTPUT
C	JNEW			I*4	SECONDA DIMENSIONE MATRICE OUTPUT
C
C	OUT:
C	MATNEW(INEW,JNEW)	4BYTE	MATRICE IN OUTPUT
COMEND

	character which*(*),QUALE(7)*10
	DIMENSION MAT(IMAX,JMAX),MATNEW(INEW*JNEW)
	DATA QUALE/'II','JJ','IIJJ','JI','JII','JJI','JJII'/

	DO IFL=1,7
		IF(WHICH.EQ.QUALE(IFL))GOTO(1,2,3,4,5,6,7)IFL
	END DO
	DO J=1,JNEW
	   DO I=1,INEW
		MATNEW(I+(J-1)*INEW)=MAT(I,J)		!NESSUNO SCAMBIO
	   END DO
	END DO
	RETURN

1	CONTINUE
	DO J=1,JNEW
	   DO I=1,INEW
		MATNEW(I+(J-1)*INEW)=MAT(INEW+1-I,J)		!SCAMBIO I
	   END DO
	END DO
	RETURN

2	CONTINUE
	DO J=1,JNEW
	   DO I=1,INEW
		MATNEW(I+(J-1)*INEW)=MAT(I,JNEW+1-J)		!SCAMBIO J
	   END DO
	END DO
	RETURN

3	CONTINUE
	DO J=1,JNEW
	   DO I=1,INEW
		MATNEW(I+(J-1)*INEW)=MAT(INEW+1-I,JNEW+1-J)	!SCAMBIO I,J
	   END DO
	END DO
	RETURN

4	CONTINUE
	DO J=1,JNEW
	   DO I=1,INEW
		MATNEW(I+(J-1)*INEW)=MAT(J,I)			!SCAMBIO   +I,J
	   END DO
	END DO
	RETURN

5	CONTINUE
	DO J=1,JNEW
	   DO I=1,INEW
		MATNEW(I+(J-1)*INEW)=MAT(J,INEW+1-I)		!SCAMBIO I +I,J
	   END DO
	END DO
	RETURN

6	CONTINUE
	DO J=1,JNEW
	   DO I=1,INEW
		MATNEW(I+(J-1)*INEW)=MAT(JNEW+1-J,I)		!SCAMBIO J +I,J
	   END DO
	END DO
	RETURN

7	CONTINUE
	DO J=1,JNEW
	   DO I=1,INEW
		MATNEW(I+(J-1)*INEW)=MAT(JNEW+1-J,INEW+1-I)	!SCAMBIO J +I,J
	   END DO
	END DO

	RETURN
	END

C	PARAMETER IMAX=100,JMAX=100,INEW=2,JNEW=3
C
C	DIMENSION MAT(IMAX,JMAX),MATNEW(IMAX,JMAX)
C
C	DO I=1,INEW
C	DO J=1,JNEW
C		MAT(I,J)=I*10+J
C	END DO
C	END DO
C
C	CALL VEDI(MAT,INEW,JNEW)
C
C	CALL RIBALTA(' ',MAT,IMAX,JMAX,MATNEW,INEW,JNEW)
C	CALL VEDI(MATNEW,INEW,JNEW)
C	CALL RIBALTA('II',MAT,IMAX,JMAX,MATNEW,INEW,JNEW)
C	CALL VEDI(MATNEW,INEW,JNEW)
C	CALL RIBALTA('JJ',MAT,IMAX,JMAX,MATNEW,INEW,JNEW)
C	CALL VEDI(MATNEW,INEW,JNEW)
C	CALL RIBALTA('IIJJ',MAT,IMAX,JMAX,MATNEW,INEW,JNEW)
C	CALL VEDI(MATNEW,INEW,JNEW)
C	CALL RIBALTA('JI',MAT,IMAX,JMAX,MATNEW,JNEW,INEW)
C	CALL VEDI(MATNEW,JNEW,INEW)
C	CALL RIBALTA('JII',MAT,IMAX,JMAX,MATNEW,JNEW,INEW)
C	CALL VEDI(MATNEW,JNEW,INEW)
C	CALL RIBALTA('JJI',MAT,IMAX,JMAX,MATNEW,JNEW,INEW)
C	CALL VEDI(MATNEW,JNEW,INEW)
C	CALL RIBALTA('JJII',MAT,IMAX,JMAX,MATNEW,JNEW,INEW)
C	CALL VEDI(MATNEW,JNEW,INEW)
C
C	STOP 
C	END
C
C	SUBROUTINE VEDI(MAT,I,J)
C
C	DIMENSION MAT(I,J)
C
C	DO JJ=1,J
C	TYPE*, (MAT(II,JJ),II=1,I)
C	END DO
C
C	TYPE*,'------------------------------------------------------'
C	RETURN
C	END
C
