      SUBROUTINE KLTWIN()
      COMMON/TWIN/LWIN,LCOL
      COMMON/LWADD/LWADDR
      COMMON/DAVESX/IVAL 
      LWIN=0 
      LCOL=0
      IVAL = 0
      LWADDR = LADDR(IVAL)
      RETURN
      END
C
C HELPER FOR read_area
      SUBROUTINE RHELP(IAREA, INBYTS)
      CALL ARAOPT(IAREA, 1, 'UNIT', LIT('BRIT'))
      CALL ARAOPT(IAREA, 1, 'SPAC', INBYTS)
      RETURN
      END
